trigger:
- main
pool:
  vmImage: ubuntu-latest
variables:
- name: DEV_ENVIRONMENT
  value: dev
- name: QA_ENVIRONMENT
  value: qa 
stages:
- stage: TerraformValidate
  displayName: Validate Terraform
  jobs:
  - job: TerraformValidateJob
    displayName: Terraform Validate Job
    continueOnError: false
    steps:
    - task: PublishPipelineArtifact@1
      displayName: Publish Terraform Manifest Artifacts
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/Terraform-manifest' # copying terraform manifest from Terraform-manifest to Terraform-manifest-out to use in deployment stage
        artifact: 'Terraform-manifest-out'
        publishLocation: 'pipeline'  # This is the location in Ubuntu where Terraform-manifest-out file will store
    - task: TerraformCLI@2
      displayName: Terraform Init
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform-manifest'
        backendType: 'azurerm'
        backendServiceArm: 'terraform-aks-azurerm-svc-con'
        backendAzureRmResourceGroupName: 'Ganesh-rg'
        backendAzureRmStorageAccountName: 'ganeshstorageact'
        backendAzureRmContainerName: 'ganeshstoragecontainer'
        backendAzureRmKey: 'tfcluster.tfstate'
        allowTelemetryCollection: false
    - task: TerraformCLI@2
      displayName: Terraform Validate
      inputs:
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform-manifest'
        allowTelemetryCollection: false

- stage: DeployStorageAccount 
  displayName: Deploy Storage Account
  jobs:
    - deployment: DeployDevStorageAccounts
      displayName: Deploy Dev Storage Accounts
      pool:
        vmImage: ubuntu-latest
      environment: $(DEV_ENVIRONMENT)
      strategy:
       runOnce:
         deploy:
           steps:
            - task: TerraformCLI@2
              displayName: Terraform Init
              inputs:
                command: 'init'
                workingDirectory: '$(Pipeline.Workspace)/Terraform-manifest-out'
                backendType: 'azurerm'
                backendServiceArm: 'terraform-aks-azurerm-svc-con'
                backendAzureRmResourceGroupName: 'Ganesh-rg'
                backendAzureRmStorageAccountName: 'ganeshstorageact'
                backendAzureRmContainerName: 'ganeshstoragecontainer'
                backendAzureRmKey: 'tfcluster.tfstate'
                allowTelemetryCollection: false
            - task: TerraformCLI@2
              displayName: Terraform Plan
              inputs:
                command: 'plan'
                workingDirectory: '$(Pipeline.Workspace)/Terraform-manifest-out'
                environmentServiceName: 'terraform-aks-azurerm-svc-con'
                allowTelemetryCollection: false
            - task: TerraformCLI@2
              displayName: Terraform Apply
              inputs:
                command: 'apply'
                workingDirectory: '$(Pipeline.Workspace)/Terraform-manifest-out'
                environmentServiceName: 'terraform-aks-azurerm-svc-con'
                allowTelemetryCollection: true
